"""add_source_metadata_column

Revision ID: 29e7bd63663d
Revises: bf08a1fb57b7
Create Date: 2025-11-04 07:30:20.513661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29e7bd63663d'
down_revision: Union[str, None] = 'bf08a1fb57b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declarations', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('declarations', 'source_metadata')
    # ### end Alembic commands ###
