"""Add importers and exporters master data tables

Revision ID: 2e5400006f94
Revises: f5a72c9e8b3d
Create Date: 2025-11-07 09:35:34.951616

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e5400006f94'
down_revision: Union[str, None] = 'f5a72c9e8b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('address_line3', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('first_seen_declaration_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_declaration_id', sa.UUID(), nullable=True),
    sa.Column('declaration_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('last_reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['last_reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name_normalized', 'country_code', name='uq_exporter_org_name_country')
    )
    op.create_index('idx_exporter_country_code', 'exporters', ['country_code'], unique=False)
    op.create_index('idx_exporter_deleted_at', 'exporters', ['deleted_at'], unique=False)
    op.create_index('idx_exporter_name_normalized', 'exporters', ['name_normalized'], unique=False)
    op.create_index('idx_exporter_org_id', 'exporters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_exporters_country_code'), 'exporters', ['country_code'], unique=False)
    op.create_index(op.f('ix_exporters_deleted_at'), 'exporters', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_exporters_name_normalized'), 'exporters', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_exporters_organization_id'), 'exporters', ['organization_id'], unique=False)
    op.create_table('importers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tax_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('first_seen_declaration_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_declaration_id', sa.UUID(), nullable=True),
    sa.Column('declaration_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('last_reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['last_reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'tax_code', 'deleted_at', name='uq_importer_org_tax_code')
    )
    op.create_index('idx_importer_deleted_at', 'importers', ['deleted_at'], unique=False)
    op.create_index('idx_importer_name_normalized', 'importers', ['name_normalized'], unique=False)
    op.create_index('idx_importer_org_id', 'importers', ['organization_id'], unique=False)
    op.create_index('idx_importer_tax_code', 'importers', ['tax_code'], unique=False)
    op.create_index(op.f('ix_importers_deleted_at'), 'importers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_importers_name_normalized'), 'importers', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_importers_organization_id'), 'importers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_importers_tax_code'), 'importers', ['tax_code'], unique=False)
    op.add_column('declarations', sa.Column('importer_id', sa.UUID(), nullable=True))
    op.add_column('declarations', sa.Column('exporter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_declarations_exporter_id'), 'declarations', ['exporter_id'], unique=False)
    op.create_index(op.f('ix_declarations_importer_id'), 'declarations', ['importer_id'], unique=False)
    op.create_foreign_key(None, 'declarations', 'importers', ['importer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'declarations', 'exporters', ['exporter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'declarations', type_='foreignkey')
    op.drop_constraint(None, 'declarations', type_='foreignkey')
    op.drop_index(op.f('ix_declarations_importer_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_exporter_id'), table_name='declarations')
    op.drop_column('declarations', 'exporter_id')
    op.drop_column('declarations', 'importer_id')
    op.drop_index(op.f('ix_importers_tax_code'), table_name='importers')
    op.drop_index(op.f('ix_importers_organization_id'), table_name='importers')
    op.drop_index(op.f('ix_importers_name_normalized'), table_name='importers')
    op.drop_index(op.f('ix_importers_deleted_at'), table_name='importers')
    op.drop_index('idx_importer_tax_code', table_name='importers')
    op.drop_index('idx_importer_org_id', table_name='importers')
    op.drop_index('idx_importer_name_normalized', table_name='importers')
    op.drop_index('idx_importer_deleted_at', table_name='importers')
    op.drop_table('importers')
    op.drop_index(op.f('ix_exporters_organization_id'), table_name='exporters')
    op.drop_index(op.f('ix_exporters_name_normalized'), table_name='exporters')
    op.drop_index(op.f('ix_exporters_deleted_at'), table_name='exporters')
    op.drop_index(op.f('ix_exporters_country_code'), table_name='exporters')
    op.drop_index('idx_exporter_org_id', table_name='exporters')
    op.drop_index('idx_exporter_name_normalized', table_name='exporters')
    op.drop_index('idx_exporter_deleted_at', table_name='exporters')
    op.drop_index('idx_exporter_country_code', table_name='exporters')
    op.drop_table('exporters')
    # ### end Alembic commands ###
