"""add_processing_log_field

Revision ID: d9d214d3418e
Revises: 29e7bd63663d
Create Date: 2025-11-04 08:10:21.119240

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd9d214d3418e'
down_revision: Union[str, None] = '29e7bd63663d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
