"""Initial schema with core models

Revision ID: e3061fd0812f
Revises: 
Create Date: 2025-10-18 09:19:26.191258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3061fd0812f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create PostgreSQL extensions
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm";')

    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('processor', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'VALIDATING', 'READY_FOR_REVIEW', 'APPROVED', 'REJECTED', 'FAILED', name='declarationstatus'), nullable=False),
    sa.Column('uploaded_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_progress', sa.Float(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declarations_created_at'), 'declarations', ['created_at'], unique=False)
    op.create_index(op.f('ix_declarations_organization_id'), 'declarations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_declarations_status'), 'declarations', ['status'], unique=False)
    op.create_table('knowledge_base_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('GOOD_LIST', 'TARIFF', name='knowledgebasetype'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='knowledgebasestatus'), nullable=False),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'type', 'version_number', name='uq_knowledge_base_version')
    )
    op.create_index(op.f('ix_knowledge_base_versions_organization_id'), 'knowledge_base_versions', ['organization_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('declaration_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('original_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('correction_type', sa.Enum('TYPO', 'WRONG_EXTRACTION', 'WRONG_HS_CODE', 'VALIDATION_FIX', 'OTHER', name='correctiontype'), nullable=False),
    sa.Column('source_document', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_created_at'), 'corrections', ['created_at'], unique=False)
    op.create_index(op.f('ix_corrections_declaration_id'), 'corrections', ['declaration_id'], unique=False)
    op.create_index(op.f('ix_corrections_field_name'), 'corrections', ['field_name'], unique=False)
    op.create_table('good_list_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('hs_code', sa.String(length=8), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_base_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_good_list_entries_organization_id'), 'good_list_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_good_list_entries_version_id'), 'good_list_entries', ['version_id'], unique=False)
    op.create_table('tariff_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hs_code', sa.String(length=8), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('import_duty_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('trade_agreement', sa.String(length=50), nullable=True),
    sa.Column('description_vi', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_base_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_rates_hs_code'), 'tariff_rates', ['hs_code'], unique=False)
    op.create_index(op.f('ix_tariff_rates_is_active'), 'tariff_rates', ['is_active'], unique=False)
    op.create_index(op.f('ix_tariff_rates_organization_id'), 'tariff_rates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tariff_rates_version_id'), 'tariff_rates', ['version_id'], unique=False)

    # Create GIN indexes for JSONB and full-text search
    op.execute('CREATE INDEX idx_declarations_draft_data ON declarations USING GIN (draft_data);')
    op.execute('CREATE INDEX idx_goodlist_description_trgm ON good_list_entries USING GIN (product_description gin_trgm_ops);')

    # Create trigger function for auto-updating updated_at columns
    op.execute('''
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    ''')

    # Apply triggers to tables with updated_at column
    op.execute('''
        CREATE TRIGGER update_users_updated_at
        BEFORE UPDATE ON users
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    ''')
    op.execute('''
        CREATE TRIGGER update_declarations_updated_at
        BEFORE UPDATE ON declarations
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    ''')
    op.execute('''
        CREATE TRIGGER update_organizations_updated_at
        BEFORE UPDATE ON organizations
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop triggers
    op.execute('DROP TRIGGER IF EXISTS update_organizations_updated_at ON organizations;')
    op.execute('DROP TRIGGER IF EXISTS update_declarations_updated_at ON declarations;')
    op.execute('DROP TRIGGER IF EXISTS update_users_updated_at ON users;')
    op.execute('DROP FUNCTION IF EXISTS update_updated_at_column();')

    # Drop custom GIN indexes
    op.execute('DROP INDEX IF EXISTS idx_goodlist_description_trgm;')
    op.execute('DROP INDEX IF EXISTS idx_declarations_draft_data;')

    op.drop_index(op.f('ix_tariff_rates_version_id'), table_name='tariff_rates')
    op.drop_index(op.f('ix_tariff_rates_organization_id'), table_name='tariff_rates')
    op.drop_index(op.f('ix_tariff_rates_is_active'), table_name='tariff_rates')
    op.drop_index(op.f('ix_tariff_rates_hs_code'), table_name='tariff_rates')
    op.drop_table('tariff_rates')
    op.drop_index(op.f('ix_good_list_entries_version_id'), table_name='good_list_entries')
    op.drop_index(op.f('ix_good_list_entries_organization_id'), table_name='good_list_entries')
    op.drop_table('good_list_entries')
    op.drop_index(op.f('ix_corrections_field_name'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_declaration_id'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_created_at'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_knowledge_base_versions_organization_id'), table_name='knowledge_base_versions')
    op.drop_table('knowledge_base_versions')
    op.drop_index(op.f('ix_declarations_status'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_organization_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_created_at'), table_name='declarations')
    op.drop_table('declarations')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
